### ISSUE TITLE
Need pytorch nightly?

### ISSUE THREAD

**Issue by agaldran** [t-vi/pytorch-tvmisc#5]
Hi!
Thank you for making the Wasserstein loss extension available. Forgive me if this isn't an issue, I am not an expert user. I just wanted to comment that when I tried to run the extension in my computer (`torch 1.1.0`) I was getting this error in compilation time:
```
error: identifier "TORCH_CHECK" is undefined
```
After installing the latest `pytorch-nightly` everything seems to run smoothly, so I guess this may be a requirement?

**Comment by t-vi** [comment]
Thanks for raising this! I guess
```
#ifndef TORCH_CHECK
#define TORCH_CHECK AT_CHECK
#endif
```
would be a good idea, because that indeed changed after 1.1.

**Comment by Yozey** [comment]
Hello @t-vi ,

Thank you for sharing your awesome code for the Wassertein distance.

Could you please precise your CUDA version, pytorch version and CuDNN version please? I encountered 4 errors when I was compling the CUDA code and I suspected that it is due to the complier version.

1. ` error: static assertion failed with "ArgumentInfo is to be a POD struct"`
2. `error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"`
3. `error: identifier "__shfl_xor" is undefined`
4. `error: identifier "TORCH_CHECK" is undefined` (solved by your previous response)

I'm using CUDA8.0, CuDNN 7.1.1 and PyTorch 1.0.0.

**Comment by t-vi** [comment]
You need PyTorch 1.1 and the above hotfix or PyTorch nightlies. CuDNN should not matter at all, CUDA8 probably works.

**Comment by t-vi** [comment]
This is now all well with contemporary versions of PyTorch, so I'm closing it.
